name: Data refresh

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 2'

jobs:
 update:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
       node-version: '22'

   - name: Install dependencies
     run: npm ci

   - name: Fetch data
     run: node bin/scrape.mjs

   - name: Commit files
     id: auto-commit-action
     uses: stefanzweifel/git-auto-commit-action@v5
     with:
       commit_message: Update data

   - name: Build
     if: steps.auto-commit-action.outputs.changes_detected == 'true'
     run: npm run build

   - name: Deploy
     uses: peaceiris/actions-gh-pages@v4
     if: steps.auto-commit-action.outputs.changes_detected == 'true'
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./out
